# 默认配置
seed: 42
model: densenet
backbone: densenet201
pretrained: true
loss: mse
optimizer: adam
lr: 0.0001
batch_size: 32
epochs: 100
data_dir: /home/haokuankuan/data/Fetal_Lung/dataset_for_regression/data
label_csv: /home/haokuankuan/data/Fetal_Lung/dataset_for_regression/labels.csv
train_split: /home/haokuankuan/data/Fetal_Lung/dataset_for_regression/train.txt
val_split: /home/haokuankuan/data/Fetal_Lung/dataset_for_regression/val.txt
test_split: /home/haokuankuan/data/Fetal_Lung/dataset_for_regression/test.txt
num_workers: 4
